project:
  type: website
  output-dir: docs
  
website:
  title: "Dr. Emilie Bagby"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - icon: file-earmark-person
        text: CV
        href: Ignacio-Martinez-CV.pdf
        target: _blank
      - text: "{{< ai google-scholar >}} Google Scholar"
        href: https://scholar.google.com/citations?user=mktJXM8AAAAJ
        target: _blank        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <script defer src="https://umami.martinez.fyi/script.js" data-website-id="49414263-4834-40bd-9f86-e7f28b106525"></script>
    
editor: visual

resources:
  - CNAME